import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { LangProvider } from "@ttbs/i18n";

import Footer from "./Components/Footer/Footer";
import Header from "./Components/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-w-[320px]] overflow-x-hidden`}>
        <LangProvider lang="en">
          <Header />
          {children}
          <Footer />
        </LangProvider>
      </body>
    </html>
  );
}
