import { HydrationOverlay } from "@builder.io/react-hydration-overlay";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";

import { TailwindIndicator } from "@ttbs/ui";

import Footer from "./components/footer/footer";
import Header from "./components/header";
import { ReactQueryProvider } from "./components/react-query-provider";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Easy-Boarding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <HydrationOverlay>
      <html lang="en">
        <body className={`${inter.className} bg-subtle overflow-x-hidden`}>
          {/* <LangProvider lang="en"> */}

          <ReactQueryProvider>
            <Providers lang="vi">
              <Header />

              {children}
              <Footer />
              {/* </LangProvider> */}
              <Toaster richColors />
              <TailwindIndicator />
            </Providers>
          </ReactQueryProvider>
        </body>
      </html>
    </HydrationOverlay>
  );
}
