import { dir } from "i18next";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { languages } from "@ttbs/i18n";
import { cn } from "@ttbs/lib/cn";

import Providers from "../providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return languages.map((locale) => ({ locale }));
}

export default function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode;
  params: {
    lng: string;
  };
}) {
  return (
    <html lang="en" dir={dir(lng)}>
      <body className={cn(inter.className, "light")}>
        <Providers lang={lng}>{children}</Providers>
      </body>
    </html>
  );
}
