#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# The reason we're exporting this variable is because of this issue:
# https://github.com/typicode/husky/issues/968
export FORCE_COLOR=1

echo '🔍🎨 Formating and checking staged files before committing!'

# Disable concurent to run check-types after ESLint in lint-staged
npx lint-staged --concurrent false