name: CI/CD - API Deployment

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: buildjet-4vcpu-ubuntu-2204
    name: Continuous Integration
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dangerous-git-checkout
      - uses: ./.github/actions/pnpm-install

  docker_build:
    runs-on: buildjet-4vcpu-ubuntu-2204
    name: Docker Image Build
    needs: [build]
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} #Should use token instead

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: khoavhd/ttbs-api:latest

  deploy:
    runs-on: buildjet-4vcpu-ubuntu-2204
    name: Continuous Deployment
    needs: [docker_build]
    steps:
      # - name: Deploy using ssh
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     port: 22
      #     script: |
      #       cd /root/train-ticket-booking/;docker stop ttbs-api;docker rm ttbs-api;docker pull khoavhd/ttbs-api:latest;docker-compose up -d
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@448a17bf857ead98546cfbdbe3b9d4cf979dda95
        with:
          url: http://${{ secrets.SSH_HOST }}:${{ secrets.WEBHOOK_PORT }}/hooks/redeploy-ttbs-api