name: PR Update

on:
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".github/CODEOWNERS"
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Detect changes
    runs-on: buildjet-4vcpu-ubuntu-2204
    permissions:
      pull-requests: read
    outputs:
      web: ${{ steps.filter.outputs.web }}
      dashboard: ${{ steps.filter.outputs.dashboard }}
      api: ${{ steps.filter.outputs.api }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/dangerous-git-checkout

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            web:
              - 'apps/www/**'
            dashboard:
              - 'apps/dashboard/**'
            api:
              - 'apps/api/**'

  type-check:
    name: Type check
    uses: ./.github/workflows/check-types.yml
    secrets: inherit

  # test:
  #   name: Unit tests
  #   uses: ./.github/workflows/test.yml
  #   secrets: inherit

  lint:
    name: Linters
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  build:
    name: Production build
    uses: ./.github/workflows/production-build.yml
    secrets: inherit

  build-without-database:
    name: Production build (without database)
    uses: ./.github/workflows/production-build-without-database.yml
    secrets: inherit

  analyze:
    needs: build
    uses: ./.github/workflows/nextjs-bundle-analysis.yml
    secrets: inherit

  required:
    needs: [
      lint, type-check, build,
      # test,
    ]
    if: always()
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')
        run: exit 1
